# Generated by Django 4.2.30 on 2026-07-05 02:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0004_alter_course_code_alter_course_credit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('classroom', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_schedules', to='course.course')),
                ('faculty', models.ForeignKey(limit_choices_to={'is_lecturer': True}, on_delete=django.db.models.deletion.CASCADE, related_name='teaching_schedule', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('day_of_week', 'start_time'),
            },
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('semester_start', 'Semester Start'), ('semester_end', 'Semester End'), ('holiday', 'Holiday'), ('exam', 'Examination'), ('internal', 'Internal Assessment'), ('assignment', 'Assignment Deadline'), ('practical', 'Practical/Lab Exam'), ('result', 'Result Declaration'), ('college_event', 'College Event'), ('workshop', 'Workshop')], max_length=30)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('description', models.TextField(blank=True)),
                ('course', models.ForeignKey(blank=True, help_text='Leave blank for an institution-wide event.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='academic_events', to='course.course')),
            ],
            options={
                'ordering': ('start_at', 'title'),
            },
        ),
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.UniqueConstraint(fields=('course', 'day_of_week', 'start_time'), name='unique_course_class_time'),
        ),
    ]
