# Generated by Django 4.2.30 on 2026-07-05 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_classschedule_academicevent_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='classschedule',
            constraint=models.CheckConstraint(check=models.Q(('end_time__gt', models.F('start_time'))), name='class_ends_after_it_starts'),
        ),
    ]
