# Generated by Django 4.2 on 2026-05-03 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_alter_essayquestion_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_en',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_es',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_fr',
        ),
        migrations.RemoveField(
            model_name='question',
            name='explanation_ru',
        ),
    ]
