# Generated by Django 4.2.30 on 2026-07-06 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0003_customrole_customrole_unique_custom_role_per_college'),
        ('accounts', '0004_user_tenant_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='enterprise.customrole'),
        ),
    ]
