# Generated by Django 4.0.8 on 2025-12-22 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('emotion', models.CharField(choices=[('Happy', 'Happy'), ('Neutral', 'Neutral'), ('Stressed', 'Stressed'), ('Sad', 'Sad'), ('Frustrated', 'Frustrated'), ('Tired', 'Tired'), ('Anxious', 'Anxious')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('source', models.CharField(default='face', max_length=50)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_records', to='accounts.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EmotionAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField()),
                ('is_for_teacher', models.BooleanField(default=True)),
                ('is_for_parent', models.BooleanField(default=True)),
                ('is_read', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotion_alerts', to='accounts.student')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
